name: CD
run-name: Car Parts ${{ github.event.inputs.version || '1.0.0'}}

on:
  workflow-dispatch:
    inputs:
      version:
        description: "semver format"
        required: true
        default: "1.0.0"

jobs:
  job-test:
    runs-on: ubuntu-latest
    steps:
      - name: something
        run: echo "workflow triggered with ${{ github.event.inputs.version}}"